-- vim.keymap.set("n", ".", "/")
vim.keymap.set("n", "ץ", ".")
vim.keymap.set("n", "ת", ",")
vim.keymap.set("n", "צ", "m")
vim.keymap.set("n", "מ", "n")
vim.keymap.set("n", "נ", "b")
vim.keymap.set("n", "ה", "v")
vim.keymap.set("n", "ב", "c")
vim.keymap.set("n", "ס", "x")
vim.keymap.set("n", "ז", "z")
vim.keymap.set("n", "ף", ";")
vim.keymap.set("n", "ך", "l")
vim.keymap.set("n", "ל", "k")
vim.keymap.set("n", "ח", "j")
vim.keymap.set("n", "י", "h")
vim.keymap.set("n", "ע", "g")
vim.keymap.set("n", "כ", "f")
vim.keymap.set("n", "ג", "d")
vim.keymap.set("n", "ד", "s")
vim.keymap.set("n", "ש", "a")
vim.keymap.set("n", "פ", "p")
vim.keymap.set("n", "ם", "o")
vim.keymap.set("n", "ן", "i")
vim.keymap.set("n", "ו", "u")
vim.keymap.set("n", "ט", "y")
vim.keymap.set("n", "א", "t")
vim.keymap.set("n", "ר", "r")
vim.keymap.set("n", "ק", "e")
-- vim.keymap.set("n", "'", "w")
-- vim.keymap.set("n", "/", "q")
