#!/bin/sh
bspc rule -r "*"

pgrep -x sxhkd > /dev/null || sxhkd &

#                                 (     󰙯 )
bspc monitor -d 0 1 2 3 4 5 6 7 8 9 10 11 12

bspc config window_gap           0
bspc config border_width         0

bspc config focused_border_color \#FFFFFF
bspc config normal_border_color \#000000
bspc config presel_feedback_color \#222222

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config ignore_ewmh_focus true

# rules
bspc rule -a copyq desktop=10 follow=off focus=off
bspc rule -a Spotify desktop=11 follow=off focus=off
bspc rule -a discord desktop=12 follow=off focus=off

# autoruns
picom -fb --backend glx --fade-exclude 'class_g = "xsecurelock"' &
setxkbmap us &
sxhkd &
nitrogen --restore &
xbanish & 
$HOME/.config/polybar/launch.sh &
xsetroot -cursor_name left_ptr &
xss-lock xsecurelock &
killall dunst -q &
discord &
~/scripts/notification-log.sh ~/logs/notifications.log &
pacwall &
~/scripts/enable-mouse-middle-scroll.sh &
copyq &
task sync &

notify-send "reloaded configs"

