#!/bin/sh
bspc rule -r "*"

pgrep -x sxhkd > /dev/null || sxhkd &

#                                 (     󰙯 )
bspc monitor -d 0 1 2 3 4 5 6 7 8 9 10 11 12

#bspc config window_gap           24
bspc config window_gap           0
bspc config top_padding          24
bspc config bottom_padding       24
bspc config border_width         1

bspc config focused_border_color \#FFFFFF
bspc config normal_border_color \#000000
bspc config presel_feedback_color \#111111

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config ignore_ewmh_focus true

# rules
bspc rule -a copyq desktop=10 follow=off focus=off
bspc rule -a Spotify desktop=11 follow=off focus=off
bspc rule -a discord desktop=12 follow=off focus=off
bspc rule -a discord desktop=12 follow=off focus=off
bspc rule -a Onboard state=floating

# autoruns
nitrogen --restore &
picom -b --fade-exclude 'class_g = "xsecurelock"' &
$HOME/.config/polybar/launch.sh &
~/scripts/notification-log.sh ~/logs/notifications.log &
xset -r 181  # stop the Cancel key from repeating, it is used for push to talk/mute
xset -r 133  # stop the super key from repeating, it is used for dynamic ui hiding
setxkbmap us &
xsetroot -cursor_name left_ptr &
xss-lock lock &
pacwall &
copyq &
xmodmap -e "pointer = 1, 2, 3, 4, 5, 6, 7, 11, 12, 10, 8, 9"

killall /usr/lib/kdeconnectd &
kdeconnect-cli --refresh

xbanish &
easyeffects --gapplication-service &
task sync &
discord &
transmission-daemon &
lxsession &
~/scripts/enable-mouse-middle-scroll.sh &
~/scripts/force-hide-ui-elements.sh
~/scripts/force-show-ui-elements.sh

killall dunst -q
notify-send "reloaded configs"

